---
name: Directory-Organize
version: 0.9.1
author:
  - 'Mathias Weidner <mathias@weidner.in-bad-schmiedeberg.de>'
abstract: Create and Organize Directories
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Getopt::Long: 0
  Term::ReadKey: 0
  version: 0
provides:
  Directory::Organize:
    file: lib/Directory/Organize.pm
    version: 0.9.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
